version: '3'

services:
  jenkins:
    build: 
      context: .
      dockerfile: Primerfile
    container_name: jenkins
    privileged: true
    networks:
      - jenkins
    ports:
      - "9080:8080"
      - "50000:50000"
      - "9070:9070"
    volumes:
      - /opt/jenkins_home:/var/jenkins_home
    command: --httpPort=8080
    restart: always
    environment:
      TZ: "Europe/Madrid"
    extra_hosts:
      - "dockerhost:172.17.0.1"
    depends_on:
      - prometheus
      - grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - jenkins
    ports:
      - "9090:9090"
    volumes:
      - ./Materiales/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - jenkins
    ports:
      - "3000:3000"
    restart: always

networks:
  jenkins:
