version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins-test
    privileged: true
    ports:
      - "9080:8080"
      - "50000:50000"
      - "9070:9070"
    volumes:
      - /opt/jenkins_home:/var/jenkins_home
    networks:
      - jenkins_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /opt/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - jenkins_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - jenkins_network

networks:
  jenkins_network:
    driver: bridge
